CODE :
ASSUME CS:CODE, DS:DATA
DATA SEGMENT
ORG 2000H
ARR DW 40H,20H,50H,14H,10H ;INITIALISE THE ARRAY
N EQU 05H ;INITIALISE THE NO OF ELEMENTS IN ARRAY 
DATA ENDS
CODE SEGMENT
START:
MOV AX,DATA ; MOVE DATA VALUE TO REGISTER AX
MOV DS,AX ; MOVE DATA TO DATA SEGMENT DS
MOV DX,N-1 ; MOVE N-1 TO DX REGISTER
LOOP3: 
MOV CX,DX ;INITIALISE COUNTER CX AS N-1
MOV SI,OFFSET ARR ;INITIALISE ARRAY ELEMENT INDEX TO SI
LOOP2 :
MOV AX,[SI] ;MOVE ELEMENTS FROM ARRAY AT SI TO AX
CMP [SI+2],AX ;COMPARE THEM WITH NEXT ELEMENT
JNL LOOP1 ;IF TRUE JUM TO LOOP1
XCHG [SI+2],AX
XCHG AX,[SI] ;ELSE EXCHANGE THE ELEMENTS
LOOP1: ADD SI,2 ;INCREMENT THE VALUE OF SI
LOOP LOOP2
DEC DX ;DECREMENT THE VALUE OF DX
JNZ LOOP3
HLT
CODE ENDS
END START