CODE :
ASSUME DS:DATA,CS:CODE
DATA SEGMENT ;CREATE A DATA SEGMENT 
ARR DW 0CA05H,0A012H,0AB45H,0055H,0AA63H,0007H ;ENTER THE ELEMENTS INTO ARRAY 
;2 POSITIVE AND 4 NEGATIVE
N EQU 06H ; NO OF ELEMENTS IN THE ARRAY
DATA ENDS
CODE SEGMENT
START:
MOV AX,DATA ;ASSIGN CODE SEGMENT TO CS AND DATA SEGMENT TO DS REGSISTERS 
MOV DS,AX ;MOVE THE ADDRESS OF DATA SEGMENT TO DS REGISTER USING AX
LEA SI,ARR ;MOVE THE OFFSET ADDRESS OF ARRAY TO SI REGISTER 
MOV CX,N ;MOVE THE COUNT VALUE TO CX REGISTER
XOR BX,BX ;TO MAKE THE VALUE OF BX AS 0
XOR DX,DX ;TO MAKE THE VALUE OF DX AS 0
L1:
MOV AX,[SI] ;MOVE THE VALUE IN LOCATION POINTED BY SI REGISTER TO AX
SHL AX,01 ;LEFT SHIFT THE VALUE OF AX BY 1 TO SEE IF THE MSB IS 1 OR 0
JC NG ;IF CARRY IS GENERATED JUMP TO LOOP NG-FOR NEGATIVE
INC BX ;ELSE INCREMENT BX - COUNTER FOR POSITIVE NUMBER
JMP NEXT
NG:
INC DX ;INCREMENT DX - COUNTER FOR NEGATIVE NUMBER
NEXT:
ADD SI,02 ;INCREASE SI FOR NEXT LOOP
DEC CX ;DECREMENT COUNTER VALUE CX
JNZ L1
HLT
CODE ENDS
END START