CODE :
ASSUME CS:CODE, DS:DATA
DATA SEGMENT ;CREATE A DATA SEGMENT
ORG 2000H ;ARRAY ADDRESS
RES DB 08H DUP(0) ;ARRAY INITIALISED TO ALL VALUE AS 0
DATA ENDS
CODE SEGMENT
START:
MOV AX,DATA ;ASSIGN CODE SEGMENT TO CS 
MOV DS,AX ; MOVE THE ADDRESS OF DATA SEGMENT TO DS REGISTER USING AX
LEA SI,RES ; MOVE THE OFFSET ADDRESS OF ARRAY TO SI REGISTER
MOV CX,08H ;MOVE THE COUNT VALUE TO CX REGISTER
MOV AX,00H ;THE VALUE OF AX AS 0
MOV [SI],00H ;INITIALISE THE VALUE OF FIRST ELEMENT IN ARRAY AS 00H
MOV [SI+1],01H ;INITIALISE THE VALUE OF 2ND ELEMENT IN ARRAY AS 01H
ADD SI,02H ;INCREMENT SI VALUE
SUB CX,02H ;COUNTER VALUE IS 2 LESS THAN CX ACTUAL COUNTER
L1:
MOV AL,[SI-1] ;MOVE THE PRIOR ELEMENT TO AL
ADD AL,[SI-2] ;ADD THE NEXT VALUE TO IT
MOV [SI],AL ;SAVE THE VALUE OF AL TO ARRAY
INC SI ;INCREMENT SI 
LOOP L1 ;LOOPING
HLT
CODE ENDS
END START