CODE :

ASSUME CS:CODE,DS:DATA 

DATA SEGMENT         ;CREATE A DATA SEGMENT
N EQU 05 H                    ;WE INITIALIZE N VALUE TO 5
R EQU 03H                     ;WE INITIALIZE R VALUE TO 3
DATA ENDS 

CODE SEGMENT 
START: 
MOV AX,DATA         ;MOVE DATA VALUE TO REGISTER AX
MOV DS,AX             ;MOVE VALUE OF AX REGISTER TO REGISTER DX
MOV AX,N            ;INITIALIZE AX TO N
MOV CX,AX            ;INITIALIZE CX TO N 
CALL FAC            ;CALCULATE THE FACTORIAL OF CX (N)
PUSH AX            ;RESULT IS STORED IN AX AND IT IS PUSHED TO STACK
MOV CX,N            ;INITIALIZE CX TO N
SUB CX,R             ;CX VALUE CHANGED TO N-R
CALL FAC            ;CALCULATE (N-R)!
PUSH AX            ;RESULT IS STORED IN AX AND IT IS PUSHED TO STACK
XOR AX,AX            ;REMOVING ANY RESIDUAL OR GARBAGE VALUE
XOR BX,BX            ;REMOVING ANY RESIDUAL OR GARBAGE VALUE
POP BX                ; RETRIEVE FACT(N-R) IN BX
POP AX            ; RETRIEVE FACT(N) IN AX
DIV BX                ;DIVIDE AX BY BX I.E N!/(N-R)! AND STORE IT IN AX
HLT 

FAC PROC NEAR         ;FACTORIAL FUNCTION DECLARATION
XOR DX,DX            ;REMOVING ANY RESIDUAL OR GARBAGE VALUE
MOV AX,0001H         ; INITIALIZE AX TO 1 
LP1: 
MUL CX             ;MUTLIPLYING AX AND CX (CX IS THE COUNTER VALUE)
LOOP LP1 
RET                 ;RETURNING THE RESULT
FAC ENDP

CODE ENDS 
END START