CODE :
ASSUME CS:CODE,DS:DATA
DATA SEGMENT ; CREATE A DATA SEGMENT
NUM EQU 144 ; INITIALISE THE VALUE OF N AS REQUIRED 
DATA ENDS
CODE SEGMENT
START:
MOV CX,01 ;COUTER VALUE OF CX INITIALISED TO 1
LOOP1:
INC CX ;INCREMENT THE VALUE OF CX
MOV AX,CX ;MOVE CX INTO AX FOR MULTIPLICATION
MUL CX ;MULTIPLYING AX AND CX STORED IN AX
CMP AX,NUM ;COMPARE AX AND NUMBER NUM
JNE LOOP1 ;IF NOT TRUE THEN CONTINUE THE LOOP
MOV AX,CX ;MOV CX VALUE TO AX
HLT
CODE ENDS
END START